version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet pack
      - run: dotnet test --no-build
      - run: dotnet nuget push src/KingpinNet/bin/Debug/KingpinNet.0.1.0.nupkg -k oy2eorzfj6vz5pvshgnacpq3z4mn2t2uzndiyhqucvds5e -s https://api.nuget.org/v3/index.json
