version: 2.1

executors:
  dotnetcore:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    working_directory: /source

jobs:
  build:
    executor: dotnetcore
    steps:
      - checkout
      - run: dotnet restore
      - run: sed 's/buildversion/'"$CIRCLE_BUILD_NUM"'/g' src/KingpinNet/KingpinNet.nuspec > src/KingpinNet/KingpinNet.final.nuspec
      - run: dotnet build
      - run: dotnet test --no-build --logger "junit;LogFilePath=results.xml"
      - run: dotnet pack src/KingpinNet -o /source/workspace/packages
      - run: find .

      - store_test_results:
          path: test

      - store_artifacts:
          path: /source/workspace/packages

      - persist_to_workspace:
          root: /source/workspace
          paths:
            - packages

  deploy:
    executor: dotnetcore
    steps:
      - attach_workspace:
          at: /source/workspace
      - run: find .
      - run: dotnet nuget push ./workspace/packages/KingpinNet.0.3.$CIRCLE_PREVIOUS_BUILD_NUM.nupkg -k oy2p2skw7v6pejpnxs2qis6mmd3a5zpubouqcb3uxan5pe -s https://api.nuget.org/v3/index.json

workflows:
  version: 2

  buildtestdeploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
