version: 2.1

executors:
  dotnetcore:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    working_directory: /tmp

jobs:
  build:
    executor: dotnetcore
    steps:
      - checkout
      - run: 
          name: Restore NuGet packages
          command: dotnet restore

      - run: 
          name: Replace version in nuspec file
          command: sed 's/buildversion/'"$CIRCLE_BUILD_NUM"'/g' src/KingpinNet/KingpinNet.nuspec > src/KingpinNet/KingpinNet.final.nuspec

      - run:
          name: Build code
          command: dotnet build

      - run:
          name: Run tests
          command: dotnet test --no-build --logger "junit;LogFilePath=results.xml"

      - run: 
          name: Make NuGet packages
          command: dotnet pack -o /tmp

      - store_test_results:
          path: test

  deploy:
    executor: dotnetcore
    steps:
      - run:
          name: Push package to NuGet
          command: dotnet nuget push /tmp/KingpinNet.0.1.$CIRCLE_BUILD_NUM.nupkg -k oy2p2skw7v6pejpnxs2qis6mmd3a5zpubouqcb3uxan5pe -s https://api.nuget.org/v3/index.json

workflows:
  version: 2

  btd:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
