version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: sed 's/--build--/$CIRCLE_BUILD_NUM/g' src/KingpinNet/KingpinNet.nuspec > src/KingpinNet/KingpinNet.nuspec
      - run: dotnet build
      - run: dotnet pack
      - run: dotnet test --no-build
      - run: dotnet nuget push src/KingpinNet/bin/Debug/KingpinNet.0.1.0.nupkg -k oy2p2skw7v6pejpnxs2qis6mmd3a5zpubouqcb3uxan5pe -s https://api.nuget.org/v3/index.json
