version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: ls
      - run: dotnet test --no-build test/UnitTests/bin/Debug/netcoreapp2.2/Tests
