version: 2.1

executors:
  my-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    working_directory: /tmp

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: 
          name: Restore NuGet packages
          command: dotnet restore

      - run: 
          name: Replace version in nuspec file
          command: sed 's/buildversion/'"$CIRCLE_BUILD_NUM"'/g' src/KingpinNet/KingpinNet.nuspec > src/KingpinNet/KingpinNet.final.nuspec

      - run:
          name: Build code
          command: dotnet build

      - run:
          name: Run tests
          command: dotnet test --no-build

      - run: 
          name: Make NuGet packages
          command: dotnet pack

  deploy:
    executor: my-executor
    steps:
      - run:
          name: Push package to NuGet
          command: dotnet nuget push src/KingpinNet/bin/Debug/KingpinNet.0.1.$CIRCLE_BUILD_NUM.nupkg -k oy2p2skw7v6pejpnxs2qis6mmd3a5zpubouqcb3uxan5pe -s https://api.nuget.org/v3/index.json

workflows:
  version: 2

  btd:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
